server:
  port: 8081 # Porta diferente do Gateway (8080) e Discovery (8761)

spring:
  application:
    name: user-service # Nome usado pelo Gateway (lb://user-service) e Eureka

  datasource:
    # 'db' é o nome do serviço definido no docker-compose.yml
    url: jdbc:mysql://db:3306/user_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root # Senha definida no environment do serviço 'db'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # Cria/Atualiza as tabelas automaticamente
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# ==================================================
# CONFIGURAÇÕES ESPECÍFICAS DA APLICAÇÃO (CORTA AÍ)
# ==================================================
app:
  security:
    jwt:
      # Use variável de ambiente ou um valor padrão para dev
      secret-key: ${JWT_SECRET_KEY:SecretKeySuperSeguraParaDesenvolvimento12345}
      expiration-ms: 3600000 # 1 hora

error:
  handling:
    http-status-in-json-response: true
    full-stacktrace-http-statuses: 5xx
