services:
  # O Banco de dados único com os 3 schemas
  db:
    image: mysql:8.0
    container_name: cortaai-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Executa o script de criação
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # O servidor que regista os outros
  discovery:
    image: eclipse-temurin:17-jdk
    container_name: discovery-service
    working_dir: /app
    volumes: ["./backend:/app"]
    command: "./mvnw spring-boot:run -pl discovery-service"
    ports: ["8761:8761"]

  # A porta de entrada para o Frontend
  gateway:
    image: eclipse-temurin:17-jdk
    container_name: api-gateway
    working_dir: /app
    volumes: ["./backend:/app"]
    command: "./mvnw spring-boot:run -pl api-gateway"
    ports: ["8080:8080"]
    depends_on: [discovery]

  # Exemplo de um serviço de negócio
  user-service:
    image: eclipse-temurin:17-jdk
    container_name: user-service
    working_dir: /app
    volumes: ["./backend:/app"]
    command: "./mvnw spring-boot:run -pl user-service"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/user_db
    depends_on: [db, discovery]

  # Frontend em React 19
  frontend:
    image: node:20
    container_name: cortaai-web
    working_dir: /app
    volumes: ["./frontend:/app"]
    ports: ["5173:5173"]
    command: "sh -c 'npm install && npm run dev -- --host'"

volumes:
  db_data:
