AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  API para a aplicação Cortaai Barber Shop

Resources:
  CortaaiApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: ifsp.edu.projeto.cortaai.StreamLambdaHandler::handleRequest
      Runtime: java17
      MemorySize: 1024
      Timeout: 60
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: prod
          # --- ATENÇÃO: Substitua os valores abaixo pelos do seu RDS ---
          # Esta é a URL do seu arquivo .env
          JDBC_DATABASE_URL: jdbc:mysql://cortaai-db.cvkm6au2ib6n.us-east-1.rds.amazonaws.com:3306/corta_ai?serverTimezone=UTC
          # Este é o seu usuário
          JDBC_DATABASE_USERNAME: admin
          # Esta é a sua senha. (Para produção real, use o AWS Secrets Manager)
          JDBC_DATABASE_PASSWORD: cortaaidb123
      Events:
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref ApiGateway # Adiciona esta linha para dar nome ao recurso API Gateway
            
# NOVO BLOCO: Configure o CORS na API Gateway
# Você pode colocar o bloco 'ApiGateway' logo após 'CortaaiApiFunction' ou no final do arquivo.
  ApiGateway: # Este é o recurso que você referenciou acima
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'https://cortaai.oneaction.space'" # Seu domínio de frontend
        AllowMethods: "'*'" # Permite todos os métodos (GET, POST, PUT, DELETE...)
        AllowHeaders: "'*'" # Permite todos os cabeçalhos

Outputs:
  ApiEndpoint:
    Description: "URL do endpoint do API Gateway para a sua aplicação"
    Value: !Sub 'https://$\{ServerlessRestApi}.execute-api.$\{AWS::Region}.amazonaws.com/Prod'
