AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  API para a aplicação Cortaai Barber Shop

Resources:
  CortaaiApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/cortaai-0.0.1-SNAPSHOT.jar
      Handler: ifsp.edu.projeto.cortaai.StreamLambdaHandler::handleRequest
      Runtime: java17
      MemorySize: 1024
      Timeout: 60
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: prod
          # --- ATENÇÃO: Substitua os valores abaixo pelos do seu RDS ---
          # Esta é a URL do seu arquivo .env
          JDBC_DATABASE_URL: jdbc:mysql://cortaai-db.cvkm6au2ib6n.us-east-1.rds.amazonaws.com:3306/corta_ai?serverTimezone=UTC
          # Este é o seu usuário
          JDBC_DATABASE_USERNAME: admin
          # Esta é a sua senha. (Para produção real, use o AWS Secrets Manager)
          JDBC_DATABASE_PASSWORD: cortaaidb123
      Events:
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiEndpoint:
    Description: "URL do endpoint do API Gateway para a sua aplicação"
    Value: !Sub 'https://$\{ServerlessRestApi}.execute-api.$\{AWS::Region}.amazonaws.com/Prod'