spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/cortaai?serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:<<YOUR_PASSWORD>>}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
        type:
          preferred_uuid_jdbc_type: CHAR
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      BarberTellUnique: BARBER_TELL_UNIQUE
      BarberEmailUnique: BARBER_EMAIL_UNIQUE
      BarberDocumentCPFUnique: BARBER_DOCUMENT_CPFUNIQUE
      CustomerTellUnique: CUSTOMER_TELL_UNIQUE
      CustomerEmailUnique: CUSTOMER_EMAIL_UNIQUE
      CustomerDocumentCPFUnique: CUSTOMER_DOCUMENT_CPFUNIQUE
      CustomerPreviousAppointmentUnique: CUSTOMER_PREVIOUS_APPOINTMENT_UNIQUE
springdoc:
  pathsToMatch: /, /api/**
