server:
  port: 8084

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://db:3306/payment_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true

mercadopago:
  access-token: ${MP_ACCESS_TOKEN}
  notification-url: ${MP_NOTIFICATION_URL:http://localhost:8080/api/payments/webhook}
  marketplace-fee-percent: 5.0

